---
title: "Anomaly Detection"
author: "Bradley Agwa"
date: '2022-04-04'
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Anomaly Detection

## Overview
We are to check whether there are any anomalies in the given sales dataset. The objective of this task being fraud detection.


## Load data

```{r}
# Installing anomalize package
#install.packages("anomalize",repos = "http://cran.us.r-project.org")
```

```{r}
# Load tidyverse and anomalize
library(tidyverse)
library(anomalize,warn.conflicts = FALSE)
library(tibbletime)
```

```{r}
# read data
forecast <- read.csv('http://bit.ly/CarreFourSalesDataset')
View(forecast)
```

```{r}
# checking the structure of our data
str(forecast)
```

```{r}
# checking the shape
dim(forecast)
```

We have 1000 observations and 2 variables.

```{r}
# converting variables to our preferred format
forecast$Date <- as.Date(forecast$Date, "%m/%d/%Y")
```

```{r}
str(forecast)
```

### Visualization

```{r}
# visualizing our sales
hist(forecast$Sales,col="blue")
```
```{r}
# Sales distribution over time
library(ggplot2)
ggplot(data = forecast, aes(x = Date, y = Sales)) +
      geom_bar(stat = "identity", fill = "green") +
      labs(title = "Sales distribution",
           x = "Date", y = "Sales(ksh)")
```


```{r}
# Ordering the data by Date
forecast = forecast %>% arrange(Date)
head(forecast)
```
```{r}
# Since our data has many records per day, 
# We get the average per day, so that the data
forecast = aggregate(Sales ~ Date , forecast , mean)
head(forecast)
```

```{r}
# Converting data frame to a tibble time (tbl_time)
# tbl_time have a time index that contains information about which column 
# should be used for time-based subsetting and other time-based manipulation,
forecast= tbl_time(forecast, Date)
class(forecast)
```

We now use the following functions to detect and visualize anomalies; 


```{r}
forecast %>%
    time_decompose(Sales) %>%
    anomalize(remainder) %>%
    time_recompose() %>%
    plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.5)
```

## Conclusion
There were no anomalies detected in the data.